# Generated by Django 3.1 on 2020-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('transaction_date', models.DateField(auto_now=True)),
                ('transaction_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
